name: Backpack
main: com.afforess.backpack.Backpack
version: 1.0a
author: Afforess

commands:
  open:
    description: Allows the player to see their current inventory page, the inventory page of their choosing in a window
    usage: /<command> <inventory page #>